# Copyright 2021 Google LLC
#
# Con licencia de Apache License, Versión 2.0 (la "Licencia");
# no puede utilizar este archivo excepto de conformidad con la Licencia.
# Puede obtener una copia de la licencia en
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# A menos que lo exija la ley aplicable o se acuerde por escrito, el software
# distribuido bajo la Licencia se distribuye "TAL CUAL",
# SIN GARANTÍAS O CONDICIONES DE NINGÚN TIPO, ya sea expresa o implícita.
# Consulte la Licencia para conocer el idioma específico que rige los permisos y
# limitaciones de la licencia.

#tiempo de ejecución : python27
#api_version : 1
#seguro para subprocesos : verdadero

#manipuladores :
#- url : /.*
#  script : main.app

#####################################################

applicacion: sw-prueba-ocasquero
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_file: favicon.ico
  upload: favicon\.ico

handlers:
- url: /holamundito
  script: main.app
 
- url: .*
  script: main-man.app

libraries:
- name: webapp2
  version: latest




  
